name: Continuous integration

on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2          

      - name: Build Docker Image
        run: docker build -t lambda-api .

      - name: Tag Docker Image
        run: docker tag lambda-api:latest ${{ steps.login-ecr.outputs.registry }}/lambda-api:latest
  
      - name: Push Docker Image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/lambda-api:latest